### ISSUE TITLE
Error with MUP only

### ISSUE THREAD

**Issue by pimalel233** [mrgrim/MUP#15]
Hi, I noticed it logs, when only running Forge 14.23.5.2838 and MUP, that there is a following error that appears even if all tweaks in MUP are set to false.

[21:15:01] [Server thread/FATAL] [net.minecraft.server.integrated.IntegratedServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.network.play.server.SPacketPlayerListHeaderFooter cannot be cast to org.gr1m.mc.mup.tweaks.hud.ISPacketPlayerListHeaderFooter
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:179) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassCastException: net.minecraft.network.play.server.SPacketPlayerListHeaderFooter cannot be cast to org.gr1m.mc.mup.tweaks.hud.ISPacketPlayerListHeaderFooter
	at org.gr1m.mc.mup.tweaks.hud.Hud.clearHudForPlayer(Hud.java:41) ~[Hud.class:?]
	at org.gr1m.mc.mup.config.MupConfig.lambda$new$2(MupConfig.java:284) ~[MupConfig.class:?]
	at org.gr1m.mc.mup.config.network.ConfigPacketHandler.handleClientConfigReceived(ConfigPacketHandler.java:149) ~[ConfigPacketHandler.class:?]
	at org.gr1m.mc.mup.config.network.CPacketMupConfig$Handler.lambda$onMessage$0(CPacketMupConfig.java:84) ~[CPacketMupConfig$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 3 more

Is it anything to worry about?
Edit: Though I will test it a bit more later, as I deleted Forge and MUP configs and it seems the error stopped appearing in logs.
Edit 2: Apparently, once you edit the config in-game and it generates filled file (instead of empty file), this error starts to appear when you start a new world. Since I need to disable few tweaks for compatibility, I need to generate the config, but then the error starts appearing, also not showing typical entriers of MUP mod making me think it is not working at all. In this case, no other mods used, something is not working correctly when using custom config, maybe config generates wrongly.

**Comment by pimalel233** [comment]
Now playing with more mods, seems like same error happened twice (normal one when world loaded, then after few minutes in flying in creative and placing blocks) which causes my screen to go white and after few more minutes game crashes.
[crash-2020-02-29_15.16.50-server.txt](https://github.com/mrgrim/MUP/files/4270428/crash-2020-02-29_15.16.50-server.txt)

**Comment by mrgrim** [comment]
I've pushed a fix for this that will be in the next release. In the meantime, I think loading the HUD tweak on both the client and server (or maybe just the server) might prevent the crash.

**Comment by MagmaSlime123** [comment]
> I've pushed a fix for this that will be in the next release. In the meantime, I think loading the HUD tweak on both the client and server (or maybe just the server) might prevent the crash.

You have 10 open issues...
